export const filterData =[{name:"Fast Food", image: require('../assets/fastfood.png, id:"0"')},
                    {name:"Rice",image:require("../assets/wali.png"),id:"1"},
                    {name:"Ugali",image:require("../assets/ugali.png"),id:"2"},
                    {name:"Chicken",image:require("../assets/kuku.png"),id:"3"},
                    {name:"Fruits",image:require("../assets/fruits.png"),id:"4"},
                    {name:"Burger",image:require("../assets/burger.png"),id:"5"},
                    {name:"Drinks",image:require("../assets/drinks.png"),id:"5"},                
                ];


export const restaurantsData = [
                    {restaurantName:"Cafeteria 1", farAway:"11.3",
                    businessAddress:"University Rd, Dar es Salaam", images:require("../assets/cafe1.jpg"),
                    averageReview:3.4,numberOfReview:37,coordinates:{lat:-26.1888612, lng:28.246326}, discount:10,deliveryTime:15,
                    collectTime:5,foodType:"Rice, Ugali, Drinks..." ,
                    productData:[{name:"Rice beans", price:1200.00,image:require("../assets/walibeans.jpg")},
                    {name:"Ugali Kuku", price:2500.00,image:require("../assets/ugalikuku.jpg")},
                    {name:"Ugali Samaki", price:2300.00,image:require("../assets/ugalifish.jpg")},
                        ],
                        id:0},
                    
                    {restaurantName:"Cafeteria 2", farAway:"11.3",
                    businessAddress:"University Rd, Dar es Salaam", images:require("../assets/cafe2.jpg"),
                    averageReview:4.2,numberOfReview:53,coordinates:{lat:-26.1875214, lng:28.398346}, discount:10,deliveryTime:10,
                    collectTime:5,foodType:"Rice, Ugali, Drinks..." ,
                    productData:[{name:"Rice beans", price:1200.00,image:require("../assets/walibeans.jpg")},
                    {name:"Nyama Choma", price:2000.00,image:require("../assets/nyamachoma.jpg")},
                    {name:"Supu", price:1500.00,image:require("../assets/supusupu.jpg")},
                        ],
                        id:1},

                    {restaurantName:"Hill Park", farAway:"14.3",
                    businessAddress:"University Rd, Dar es Salaam", images:require("../assets/hillpark.jpg"),
                    averageReview:4.0,numberOfReview:37,coordinates:{lat:-26.1765612, lng:28.246420}, discount:7,deliveryTime:17,
                    collectTime:5,foodType:"Rice, Ugali, Drinks..." ,
                    productData:[{name:"Nyama Choma", price:3500.00,image:require("../assets/nyamachoma.jpg")},
                    {name:"Ugali Kuku", price:3500.00,image:require("../assets/ugalikuku.jpg")},
                    {name:"Supu", price:3500.00,image:require("../assets/soupsoup.jpg")},
                        ],
                        id:2},

                    {restaurantName:"Yombo Cafeteria", farAway:"16.5",
                    businessAddress:"University Rd, Dar es Salaam", images:require("../assets/yombocafe.jpg"),
                    averageReview:3.7,numberOfReview:37,coordinates:{lat:-26.1888612, lng:28.246326}, discount:10,deliveryTime:25,
                    collectTime:7,foodType:"Rice, Ugali, Drinks..." ,
                    productData:[{name:"Rice beans", price:1200.00,image:require("../assets/walibeans.jpg")},
                    {name:"Ugali Kuku", price:2500.00,image:require("../assets/ugalikuku.jpg")},
                    {name:"Ugali Samaki", price:2000.00,image:require("../assets/ugalifish.jpg")},
                        ],
                        id:3}]